version: '3'

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sqlinit:/docker-entrypoint-initdb.d
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
        - 5432:5432
  app:
    depends_on:
      - db
    env_file: ./.env
    build: .
    restart: always
    ports:
      - 9090:9090
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://db:5432/$POSTGRES_DB?useSSL=false",
            "spring.datasource.username" : "$POSTGRES_USER",
            "spring.datasource.password" : "$POSTGRES_PASSWORD"
          }'

volumes:
  db_data: