pipeline {
    agent any
        stages {
            stage('jar') {
                steps {
                    bat './gradlew :grpc:clean'
                    bat './gradlew :grpc:jar'
                }
            }
            stage('start GRPC Service') {
                steps {
                        powershell 'docker-compose -f grpc\\docker-compose.yml up -d'
                }
            }
            stage('test') {
                        steps {
                                bat "./gradlew :grpc:clean"
                                bat "./gradlew :grpc:test"
                        }
            }
        }
        post {
            always {
                script {
                    powershell 'docker-compose -f grpc\\docker-compose.yml down --volumes'
                    powershell 'docker rmi grpc_app'
                        allure([
                                 includeProperties: false,
                                 jdk: '',
                                 properties: [],
                                 reportBuildPolicy: 'ALWAYS',
                                 results: [[path: 'grpc/build/allure-results']]
                                 ])
               }
            }
        }
}
